version: "3"

tasks:
  generate:
    aliases: 
      - gen
    desk: "Generate code from proto files"
    cmds:
      - protoc -I proto proto/check/check.proto --go_out=./gen/go --go_opt=paths=source_relative --go-grpc_out=./gen/go --go-grpc_opt=paths=source_relative